package com.knziha.pdoc;

public class Numbers {
	static final int PDF_IS_LINEARIZED		=	1;
	static final int PDF_NOT_LINEARIZED		=	0;
	static final int PDF_UNKNOW_LINEARIZED	=	-1;
	static final int PDFFORM_NOTAVAIL	=	0;
	static final int PDFFORM_AVAIL		=	1;
	static final int PDFFORM_NOTEXIST	=	2;

	enum PDF_DATAAVAIL_STATUS {
		PDF_DATAAVAIL_HEADER,
		PDF_DATAAVAIL_FIRSTPAGE,
		PDF_DATAAVAIL_FIRSTPAGE_PREPARE,
		PDF_DATAAVAIL_END,
		PDF_DATAAVAIL_CROSSREF,
		PDF_DATAAVAIL_CROSSREF_ITEM,
		PDF_DATAAVAIL_CROSSREF_STREAM,
		PDF_DATAAVAIL_TRAILER,
		PDF_DATAAVAIL_LOADALLCRSOSSREF,
		PDF_DATAAVAIL_ROOT,
		PDF_DATAAVAIL_INFO,
		PDF_DATAAVAIL_ACROFORM,
		PDF_DATAAVAIL_ACROFORM_SUBOBJECT,
		PDF_DATAAVAIL_PAGETREE,
		PDF_DATAAVAIL_PAGE,
		PDF_DATAAVAIL_PAGE_LATERLOAD,
		PDF_DATAAVAIL_RESOURCES,
		PDF_DATAAVAIL_DONE,
		PDF_DATAAVAIL_ERROR,
		PDF_DATAAVAIL_LOADALLFILE,
		PDF_DATAAVAIL_TRAILER_APPEND
	}

	static int CPDF_ModuleMgr_m_FileBufSize = 512;

	final static char[] _PDF_CharType;

	static {
		final String val=
				"WRRRRRRRRWWRWWRRRRRRRRRRRRRRRRRR"+
						"WRRRRDRRDDRNRNNDNNNNNNNNNNRRDRDR"+
						"RRRRRRRRRRRRRRRRRRRRRRRRRRRDRDRR"+
						"RRRRRRRRRRRRRRRRRRRRRRRRRRRDRDRR"+
						"WRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"+
						"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"+
						"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR"+
						"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRW";
		int len = val.length();
		_PDF_CharType = new char[len];
		val.getChars(0, len, _PDF_CharType, 0);
	}
}
