var trans={
     "start" : ""
    ,"foldThis" : "展开 / 折叠"
    ,"foldAll" : "折叠全部"
    ,"unfoldAll" : "展开全部"
    ,"unFoldCurrent" : "只展开当前页面"
    ,"saveCurrent" : "保存当前页面"
    ,"showAbout" : "关于…"
    ,"openTab" : "新窗口打开…"
    ,"openSearch" : "新窗口查询"
    ,"autoSearch" : "切换时自动搜索"
    ,"reSearch" : "重新搜索当前词语"

    ,"copyText" : "复制文本"
    ,"inPageSearch" : "发送到页内搜索"
    ,"anchorPageSearch" : "锚点页内搜索"
    ,"browserSearch" : "浏览器搜索"
    ,"mirrorSch" : "镜像搜索"
    ,"goBack" : "后退"
    ,"goForward" : "前进"
    ,"focusContent" : "折叠当前页面"
    ,"focusContent0" : "上一个"
    ,"focusContent1" : "下一个"

    ,"sendAdvanced" : "发送到高级搜索"

    ,"reloadDict" : "重新加载词典"
    ,"openFolder" : "打开所在文件夹"

    ,"focusMode1" : "专注模式1（折叠）"
    ,"focusMode2" : "专注模式2（限高）"
    ,"autoScroll1" : "快⇊"
    ,"autoScroll2" : "慢⇊"
    ,"autoScroll3" : "停"
    ,"autoScroll" : "中⇊"
    ,"toTop" : "顶⇈"

    ,"pageUpIcon" : "▲"
    ,"pageDownIcon" : "▼"
    ,"expandText" : "展开全文"
    ,"foldText" : "收起全文"
    ,"settings" : "页面设置"
};